name: Create Comment with Regex Match

on: 
  issues:
    types: [opened]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - run: echo "Hello World"
    - name: Checking Formatting
      run: |
        body= ${{ github.event.issue.body }}
        if [[ $body =~ \*\*Description\*\*:\s+.*\s+\*\*Acronyms\*\*:\s+.*\s+\*\*Code\*\*:\s+.*\s+```(\n|\r\n|\n\r)((.|\s+)*)(\n|\r\n|\n\r)``` ]]
        then 
        exit 0
        else 
        gh issue comment ${{ github.event.issue.number }} --body "Your formatting may be incorrect."
        fi
    
#       - uses: actions/checkout@v2

#       - uses: actions-ecosystem/action-regex-match@v2
#         id: regex-match
#         with:
#           text: ${{ github.event.issue.body }}
#           regex: '\*\*Description\*\*:\s+.*\s+\*\*Acronyms\*\*:\s+.*\s+\*\*Code\*\*:\s+.*\s+```(\n|\r\n|\n\r)((.|\s+)*)(\n|\r\n|\n\r)```'
          
#       - uses: actions-ecosystem/action-create-comment@v1
#         if: ${{ steps.regex-match.outputs.match == '' }}
#         with:
#           github_token: ${{ secrets.github_token }}
#           body: |
#             Hello, @${{ github.actor }}! Please correct your code snippet formatting.
            
