      - name: Find Comment
        uses: lisaschubeka/testSnippet@v2
        id: fc
        with:
          issue-number: 1

      - run: |
          echo ${{ steps.fc.outputs.comment-id }}
          echo ${{ steps.fc.outputs.comment-body }}
          echo ${{ steps.fc.outputs.comment-author }}
          echo ${{ steps.fc.outputs.comment-created-at }}
