name: Issue Formatting Checker
run-name: ${{ github.actor }} is checked for formatting
on: 
  issues:
    types: [opened, edited]
    
env:
  match: f
  
jobs:
  Issue-Format-Checking:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: actions/checkout@v3
        id: commentId
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: Description
      - run: |
          var=${{ steps.commentId.outputs.comment-body }}
          if [[ $var =~ \*\*Description\*\*:\s+.*\s+\*\*Acronyms\*\*:\s+.*\s+\*\*Code\*\*:\s+.*\s+```(\n|\r\n|\n\r)((.|\s+)*)(\n|\r\n|\n\r)``` ]];
          then echo "t" >> ${{ env.match }};
          fi
          echo ${{ env.match }}
  Issue-Processing:
    runs-on: ubuntu-latest
    needs: Issue-Format-Checking
    steps:
      - name: fail job
        if: ${{ env.match=='f' }}
        run: exit 1
