name: Issue Formatting Checker
run-name: ${{ github.actor }} is checked for formatting
on: 
  issues:
    types: [opened, edited]
    
env:
  match: f
  
jobs:
  Issue-Format-Checking:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: actions/checkout@v3
        id: commentId
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: Description
      - run: | 
          echo ${{ steps.commentId.outputs.comment-body }}
