name: Issue Formatting Checker
run-name: ${{ github.actor }} is checked for formatting
on: 
  issues:
    types: [opened, edited]
    
env:
  match: f
  
jobs:
  Issue-Format-Checking:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: actions/checkout@v3
        id: commentId
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: Description
      - name: ifCheck
        id: ifcheck
        run: |
          var=${{ steps.commentId.outputs.comment-body }}
          if [[ $var =~ \*\*Description\*\*:\s+.*\s+\*\*Acronyms\*\*:\s+.*\s+\*\*Code\*\*:\s+.*\s+```(\n|\r\n|\n\r)((.|\s+)*)(\n|\r\n|\n\r)``` ]];
          then echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Issue Processing   
        if: steps.ifcheck.outputs.match != 'true'
        run: exit 1
