name: Create Comment with Regex Match

on: 
  issues:
    types: [opened, edited]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

#       - uses: actions-ecosystem/action-regex-match@v2
#         id: regex-match
#         with:
#           text: ${{ github.event.comment.body }}
#           regex: '\*\*Description\*\*:\s+.*\s+\*\*Acronyms\*\*:\s+.*\s+\*\*Code\*\*:\s+.*\s+```(\n|\r\n|\n\r)((.|\s+)*)(\n|\r\n|\n\r)```'
#       - run: |
#           echo ${{ github.event.comment.body }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: 36
          body-regex: '((.|\s+)*)'
          
      - run: |
          echo ${{ steps.fc.outputs.comment-body }}

      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.fc.outputs.comment-body == 0 }}
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.actor }}! Please correct your code snippet formatting.
